(() => {
  const CONFIG=window.VL_ADMIN_CONFIG||{url:'',publishableKey:''};
  const loginView=document.getElementById('loginView'), appView=document.getElementById('appView'), loginForm=document.getElementById('loginForm'), loginError=document.getElementById('loginError');
  const list=document.getElementById('conversationList'), messages=document.getElementById('threadMessages'), active=document.getElementById('activeThread'), empty=document.getElementById('emptyThread'), title=document.getElementById('threadTitle'), meta=document.getElementById('threadMeta'), replyForm=document.getElementById('replyForm'), replyInput=document.getElementById('replyInput'), statusSelect=document.getElementById('statusSelect'), agentEmail=document.getElementById('agentEmail');
  if(!CONFIG.url||!CONFIG.publishableKey){loginError.textContent='Connect the Supabase project configuration before using this console.';loginForm.querySelector('button').disabled=true;return;}
  const sb=window.supabase.createClient(CONFIG.url,CONFIG.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
  let current=null, channel=null, conversations=[];
  const admin=async()=>{const {data:{user}}=await sb.auth.getUser();if(!user) return false; const role=user.app_metadata?.role; if(role!=='admin'){await sb.auth.signOut();loginError.textContent='This account is not authorized for the support console.';return false}agentEmail.textContent=user.email||'Admin';return true};
  const showApp=()=>{loginView.hidden=true;appView.hidden=false;loadConversations();};
  loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';const {error}=await sb.auth.signInWithPassword({email:document.getElementById('email').value,password:document.getElementById('password').value});if(error){loginError.textContent=error.message;return}if(await admin())showApp();});
  document.getElementById('signOut').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
  const loadConversations=async()=>{const q=await sb.from('support_conversations').select('*').order('last_message_at',{ascending:false});if(q.error){console.error(q.error);return}conversations=q.data||[];renderList();if(current)selectConversation(current.id)};
  const renderList=()=>{list.innerHTML='';if(!conversations.length){list.innerHTML='<div class="inbox-empty">No conversations yet.</div>';return}conversations.forEach(c=>{const b=document.createElement('button');b.className='conversation '+(current?.id===c.id?'active':'');b.innerHTML='<strong><span class="dot"></span>'+escapeHtml(c.visitor_name||'Visitor')+'</strong><small>'+escapeHtml(c.visitor_email||'Live chat')+' · '+new Date(c.last_message_at||c.created_at).toLocaleString()+'</small>';b.addEventListener('click',()=>selectConversation(c.id));list.appendChild(b)})};
  const selectConversation=async id=>{current=conversations.find(c=>c.id===id);if(!current)return;renderList();empty.hidden=true;active.hidden=false;title.textContent=current.visitor_name||'Visitor';meta.textContent=current.visitor_email||'Live chat visitor';statusSelect.value=current.status;const q=await sb.from('support_messages').select('*').eq('conversation_id',id).order('created_at',{ascending:true});messages.innerHTML='';(q.data||[]).forEach(renderMessage);messages.scrollTop=messages.scrollHeight;if(channel)sb.removeChannel(channel);channel=sb.channel('admin-thread-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages',filter:'conversation_id=eq.'+id},p=>{renderMessage(p.new);messages.scrollTop=messages.scrollHeight}).subscribe()};
  const renderMessage=m=>{const d=document.createElement('div');d.className='msg '+(m.sender_type==='admin'?'admin':'visitor');d.textContent=m.body;const t=document.createElement('time');t.textContent=new Date(m.created_at).toLocaleString();d.appendChild(t);messages.appendChild(d)};
  replyForm.addEventListener('submit',async e=>{e.preventDefault();if(!current)return;const body=replyInput.value.trim();if(!body)return;const {data:{user}}=await sb.auth.getUser();const q=await sb.from('support_messages').insert({conversation_id:current.id,sender_type:'admin',sender_id:user.id,body});if(q.error){alert(q.error.message);return}replyInput.value='';});
  statusSelect.addEventListener('change',async()=>{if(!current)return;await sb.from('support_conversations').update({status:statusSelect.value}).eq('id',current.id);current.status=statusSelect.value});
  document.getElementById('refresh').addEventListener('click',loadConversations);
  sb.auth.getSession().then(async({data})=>{if(data.session&&await admin())showApp()});
  sb.channel('admin-inbox').on('postgres_changes',{event:'*',schema:'public',table:'support_conversations'},loadConversations).subscribe();
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();