(() => {
const $=id=>document.getElementById(id),items=$('items'),sym={USD:'$',NGN:'₦',GBP:'£',EUR:'€'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addItem(desc='',qty=1,rate=0){const r=document.createElement('div');r.className='invoice-item';r.innerHTML='<input class="desc" placeholder="Service description"><input class="qty" type="number" min="1" value="'+qty+'"><input class="rate" type="number" min="0" step="0.01" value="'+rate+'"><button type="button" class="secondary remove">×</button>';r.querySelector('.desc').value=desc;items.appendChild(r)}
function today(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
function money(n){return sym[$('currency').value]+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function build(){let subtotal=0;$('pItems').innerHTML='';items.querySelectorAll('.invoice-item').forEach(r=>{const d=r.querySelector('.desc').value.trim(),q=Number(r.querySelector('.qty').value||0),rate=Number(r.querySelector('.rate').value||0),t=q*rate;subtotal+=t;if(d)$('pItems').insertAdjacentHTML('beforeend','<tr><td>'+esc(d)+'</td><td>'+q+'</td><td>'+money(rate)+'</td><td>'+money(t)+'</td></tr>')});const tax=subtotal*Number($('taxRate').value||0)/100,total=subtotal+tax;$('pNumber').textContent=$('invoiceNumber').value;$('pStatus').textContent=$('invoiceStatus').value;$('pIssue').textContent=$('issueDate').value;$('pDue').textContent=$('dueDate').value;$('pSeller').textContent=$('sellerName').value||'Vicki Lawrence';$('pSellerEmail').textContent=$('sellerEmail').value;$('pSellerAddress').textContent=$('sellerAddress').value;$('pClient').textContent=$('clientName').value||'Client Name';$('pClientEmail').textContent=$('clientEmail').value;$('pClientAddress').textContent=$('clientAddress').value;$('pSubtotal').textContent=money(subtotal);$('pTax').textContent=money(tax);$('pTotal').textContent=money(total);$('pPayment').textContent=$('paymentInstructions').value;return total}
$('addItem').onclick=()=>addItem();items.onclick=e=>{if(e.target.classList.contains('remove'))e.target.closest('.invoice-item').remove()};
$('generate').onclick=()=>{build();$('saveStatus').textContent='Invoice preview updated. Issue only after official approval.'};
$('print').onclick=()=>{build();window.print()};
$('downloadPdf').onclick=async()=>{build();if(!window.html2pdf){alert('PDF exporter is unavailable. Use Print / Save PDF.');return}const safe=($('invoiceNumber').value||'invoice').replace(/[^a-z0-9_-]/gi,'-');await window.html2pdf().set({margin:0.35,filename:safe+'.pdf',image:{type:'jpeg',quality:0.96},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'in',format:'a4',orientation:'portrait'}}).from(document.getElementById('invoicePreview')).save()};
$('email').onclick=()=>{build();const to=encodeURIComponent($('clientEmail').value||''),subject=encodeURIComponent('Invoice '+$('invoiceNumber').value+' — Vicki Lawrence special request'),body=encodeURIComponent('Hello '+($('clientName').value||'')+',\n\nPlease find your invoice '+$('invoiceNumber').value+'.\nTotal due: '+$('pTotal').textContent+'\nDue date: '+$('dueDate').value+'\n\nPlease use the payment instructions on the invoice.');window.location.href='mailto:'+to+'?subject='+subject+'&body='+body};
$('invoiceNumber').value='VL-INV-'+String(Date.now()).slice(-6);$('issueDate').value=today();$('dueDate').value=today(7);addItem('Video Shoutout',1,0);build();
})();